---
title: "Uso Libreria Reticulate"
author: "Cabeto"
date: "18/6/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reticulate

```{r}
library(reticulate)
use_python("/Users/User/anaconda3/pkgs")
#py_install("nombre del paquete")
os<-import("os")
os$listdir(".")

```

```{r}
library(reticulate)
np <- import("numpy", convert = FALSE)
x <- np$array(c(1:4))
sum <- x$cumsum()
print("Este objeto es de python")
print(sum)
print("Este objeto es de R")
py_to_r(sum)
```


```{r}
datos <- iris
head(datos)
datos_py <- r_to_py(datos)
```

```{python}
import numpy as np
import pandas as pd

r.datos_py.head()
```

## Sparse Matrix

```{r}
library(Matrix)
N <- 6
sparse_mat <- sparseMatrix(
   i = sample(N,N,replace =F),
   j = sample(N,N,replace =F),
   x = runif(N),
   dims = c(N,N)
)

sparse_mat
sparse_mat_py <- r_to_py(sparse_mat)
```

```{r}
anonaci<-1966
rep(anonaci,10)
scan()
vec<-c(16,0,1,20,1,7,88,5,1,9)
```

