---
title: "Datos Ordinales Ejemplo"
author: "Cabeto"
date: "16/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Datos Ordinales Ejemplo

```{r}
longitud <- rep(c("Muy.corto","Corto","Normal","Largo","Muy.largo"),c(25,21,19,18,17))
do_jir <- ordered(longitud, levels = c("Muy.corto","Corto","Normal","Largo","Muy.largo"))
do_jir
fjir <- ftable(do_jir) # frecuencias absolutas
fjir
faa_jir<-cumsum(fjir) # frecuencias absolutas acumuladas
fr_jir<-prop.table(fjir) # frecuencias relativas
fra_jir<-cumsum(prop.table(fjir)) # frecuencias relativas acumuladas
fra1_jir<-prop.table(cumsum(fjir)) # frecuencias relativas acumuladas - error

barplot(fjir, main = "Diagrama de Barras Frecuencias Absolutas")
barplot(faa_jir, main = "Diagrama de Barras Frecuencias Absolutas Acumuladas")
barplot(fr_jir, main = "Diagrama de Barras Frecuencias Relativas")
barplot(fra_jir, main = "Diagrama de Barras Frecuencias Relativas Acumuladas")
barplot(fra1_jir, main = "Diagrama de Barras Frecuencias Relativas Acumuladas - Error")
```



```{r}
longitud <- rep(c("Muy.corto","Corto","Normal","Largo","Muy.largo"),c(25,21,19,18,17))
zonas <- rep(c("A","B","C","D"),c(30,25,35,10))
jirafas <- data.frame(zonas,longitud)
str(jirafas)
head(jirafas)
apply(table(jirafas),MARGIN = 1, FUN = cumsum)
t(apply(table(jirafas),MARGIN = 1, FUN = cumsum))
t(apply(prop.table(table(jirafas), margin = 1),MARGIN = 1, FUN = cumsum))
# No se traspone la información para el gráfico
diagrama = apply(prop.table(table(jirafas), margin = 1),MARGIN = 1, FUN = cumsum)
barplot(diagrama, beside=TRUE, legend = TRUE, main = "Diagrama de barras de frecuencias relativas acumuladas de longitudes por zonas", args.legend = list(x="topleft",cex=0.55))

```

