---
title: "Datos Ordinales - Ejemplo 2"
author: "Cabeto"
date: "16/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Datos Ordinales - Ejemplo 2

```{r}
crabs = read.table("../../data/datacrab.txt", header = TRUE)
crabs = crabs[,-1] # Omitimos la primera columna
str(crabs)
# la variable Inf significa Infinito 
# right = FALSE sirve para indicar que los puntos de corte pertenecen al intervalo de su derecha
intervalos <- cut(crabs$width, breaks = c(21,25,29,33,Inf), right = FALSE, labels = c("21-25","25-29","29-33","33-..."))
crabs$width.rank = ordered(intervalos)
str(crabs)
Tabla = table(crabs[,c(1,6)])
Tabla
Fr.rel = round(prop.table(Tabla, margin = 1),3)
Fr.rel
Fr.rel.acu = round(apply(prop.table(Tabla, margin=1), MARGIN=1, FUN = cumsum),3)
t(Fr.rel.acu)
azul <- c("cyan","cyan4","cyan1","cyan3")
barplot(t(Fr.rel), beside = TRUE, legend = TRUE, ylim=c(0,1), col = azul, main = " Diagrama de barras de frecuencias relativas", args.legend=list(x = "topright", cex=0.55))
barplot(Fr.rel.acu, beside = TRUE, legend = TRUE, col = azul, main = "Diagrama de barras de frecuencias relativas a cumuladaas", args.legend = list(x = "topleft", cex=0.55))
```

