---
title: "Curso de Estadistica Descriptiva - Gráficas"
author: "Cabeto"
date: "29/6/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Graficos con la función `plot`
```{r primer_plot, fig.cap="Gráfico básico explicando el uso del plot", fig.align='center'}
x = c(2,6,4,9,-1)
y = c(1,8,4,-2,4)
plot(x,y) 

```

Si no incorporamos vector `y` y `R` nos va a tomar el parámetro `x` como si fuera el vector de datos `y` : `plot(1:n,x`
```{r}
plot(2^(1:6))
```

Si queremos representar una función $f(x)$
```{r}
f <- function(x){sqrt(x)}
plot(f)
```

## Parámetros
```{r fig.align='center'}
n = 1:20
fib = (1/sqrt(5))*((1+sqrt(5))/2)^n - (1/sqrt(5))*((1-sqrt(5))/2)^n
fib
par(mfrow = c(1,2))
plot(fib, xlab = "n", ylab = expression(F[n]), main = "Sucesión de Fibonacci - Escala Lineal", pch = 21, cex = 2, col = "powderblue", bg ="orchid") # bg = fondo del pch

plot(fib, xlab = "n", ylab = expression(F[n]), main = "Sucesión de Fibonacci - Escala Logarítmica", pch = 21, cex = 2, col = "powderblue", bg ="orchid", log = "xy")

```
Tipos de Graficos
```{r}
par(mfrow = c(3,2))
x = c(50:59)
y = c(2,9,25,3,100,77,62,54,19,40)
plot(x,y, pch=23, cex=2, col="blue", type = "p")
plot(x,y,pch=23,cex=2,col="blueviolet",type = "l")
plot(x,y,pch=23,cex=2,col="gold",type = "b")
plot(x,y,pch=23,cex=2,col="deeppink",type = "o")
plot(x,y,pch=23,cex=2,col="springgreen",type = "h")
plot(x,y,pch=23,cex=2,col="firebrick1",type = "s")
par(mfrow = c(1,1))
x = (2*(1:20))
y = (-1)^(1:20)*5*(1:20)
plot(x,y,pch=8,main = "Ejemplo de grafico", cex=1,col="chocolate1",type = "b", lty = 4, lwd = 4, xaxp=c(0,40,2), yaxp = c(-100,100,8))
points(20,0, col = "red", cex = 4, pch=16)
abline(h=0, lty =2, col ="dodgerblue")


```

## Como añadir elementos a un gráfico

```{r}
f <- function(x){
  x^2-2*x+sqrt(abs(x))
}
plot(f, xlim = c(-3,3)) # graficamos la función
points(0,0,pch=19) # Un Punto
points(-3:3, (-3:3)^2,col ="blue") # Parabola
abline(2,3, lty = "dashed", col = "red") # linea recta
abline(v = 2, lty = "dotted",lwd = 3, col = "green") #linea Vertical
abline(h = 5, lty = "dotdash",lwd = 3, col = "gray") # Linea Horizontal
```

Parabola
```{r}
f <- function(x){x^2}
plot(f, xlim = c(-3,3), col = "red", lwd = 2, ylab = expression(y^2), xlab = "x")
abline(h = 0:9, v = -3:3, lty = "dotted", col = "gray")
```

```{r}
plot(tan, xlim = c(-pi,pi))
```

```{r}
plot(tan, xlim = c(-pi,pi), ylim = c(-5,5))
abline (v = c(-pi/2,pi/2), col = "red") #asintota Vertical
```

```{r}
alumnos = c(1:10)
notas = c(2,5,7,9,8,3,5,6,10,7)
plot(alumnos,notas, main="Gráfico con Texto")
text(alumnos,notas, labels = c("S","A","N","E","N","S","A","A","E","N"), pos = c(rep(3,times =8),1,3))
```

```{r}
plot(0,0)
text(0,0, labels = "debajo", pos = 1)
text(0,0, labels = "izquierda", pos = 2)
text(0,0, labels = "arriba", pos = 3)
text(0,0, labels = "derecha", pos = 4)
points(0,1)
text(0,1,labels = "centro")
```

```{r}
f <- function(x){x^2}
plot(f, xlim =c(-3,3))
points(-3:3,f(-3:3), pch=19)
lines(-3:3,f(-3:3),  lwd=2, lty ="dotted", col = "red")
curve(x^3, lty = "dashed", col = "blue", add = TRUE)
curve(x^4, lty = "dashed", col = "orangered", add = TRUE)
legend("bottomright", legend = c(expression(x^2),expression(x^3),expression(x^4)), lwd=2, col = c("red","blue","orangered"), lty = c("dotted","dashed","dashed") )
```

```{r}
x = seq(0,2*pi,0.1)
plot(x,sin(x),type="l",col = "blue", lwd=3,xlab="",ylab="")
lines(x,cos(x), col="green",lwd=3)
lines(x,tan(x),col="purple",lwd=3)
legend("bottomleft", col = c("blue","green","purple"), legend = c("Seno","Coseno","Tangente"),lwd=3, bty="l")
```

```{r}
x = c(5*(1:10))
plot(x,c(exp(-x)+(-1)^x*x/2*sin(x)^2), xlab="", ylab="", main="Gráfico con varios elementos")
segments(10,0,40,0,col ="red", lwd=4)
arrows(10,0,40,-10, col="blue", length = 0.5, angle=5,code=3)
symbols(40,0,stars = cbind(1,.5,1,.5,1,.5,1,.5,1,.5), add =TRUE, lwd=3,inches = 0.5)
symbols(40,0,stars = cbind(1,.5,1,.5,1,.5,1,.5,1,.5), add =TRUE, lwd=3)
polygon(c(20,30,40),c(10,-10,10), col ="gold", density = 3,angle=90,lty=4)
```

